- name: sysctl
  hosts: all
  become: true

  vars:
    sysctl_config:
      net.core.default_qdisc: fq
      net.ipv4.tcp_congestion_control: bbr
      net.ipv4.tcp_slow_start_after_idle: 0
      net.ipv4.tcp_mtu_probing: 1
      net.ipv4.tcp_synack_retries: 2
      net.ipv4.tcp_rfc1337: 1
      net.ipv4.conf.all.accept_redirects: 0
      net.ipv4.conf.all.secure_redirects: 0
      net.ipv4.conf.all.send_redirects: 0
      net.ipv4.conf.all.accept_source_route: 0
      net.ipv4.conf.lo.accept_source_route: 0
      net.ipv4.conf.eth0.accept_source_route: 0
      net.ipv4.conf.default.accept_source_route: 0
      net.ipv4.tcp_max_orphans: 131072
      net.ipv4.tcp_orphan_retries: 1
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.conf.all.rp_filter: 1
      net.ipv4.conf.lo.rp_filter: 1
      net.ipv4.conf.eth0.rp_filter: 1
      net.ipv4.conf.default.rp_filter: 1
      net.core.netdev_max_backlog: 1000
      net.ipv4.tcp_fin_timeout: 10
      net.ipv4.tcp_keepalive_time: 180
      net.ipv4.tcp_keepalive_intvl: 30
      net.ipv4.tcp_keepalive_probes: 3
      net.ipv4.tcp_max_syn_backlog: 2048
      net.ipv4.icmp_echo_ignore_broadcasts: 1
      net.ipv4.icmp_ignore_bogus_error_responses: 1
      net.core.somaxconn: 65535
      net.ipv4.tcp_fastopen: 2
      net.ipv4.ip_local_port_range: 32768 61000
      net.ipv4.tcp_dsack: 0
      net.ipv4.tcp_ecn: 0
      net.ipv4.tcp_fack: 0
      net.ipv4.tcp_low_latency: 1
      net.ipv4.tcp_no_metrics_save: 1
      net.ipv4.tcp_retries2: 10
      net.ipv4.tcp_sack: 1
      net.ipv4.tcp_syncookies: 2
      net.ipv4.tcp_window_scaling: 1

  tasks:
    - name: sysctl-settings
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        reload: true
      with_dict: "{{ sysctl_config }}"
