name: lint
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ansible-lint
        run: | 
          pip install "ansible-lint[yamllint]"
          ansible-lint .

