name: lint
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: ansible-lint
        run: | 
          pip install "ansible-lint[yamllint]"
          /home/runner/.local/bin/ansible-lint -p  ${{ github.workspace }}/sysctl/sysctl_vars.yaml

